[tool.poetry]
name = "rhinventory"
version = "0.1.0"
description = ""
authors = ["Sanqui <me@sanqui.net>", "Tomáš Čapek <tomas@capek.io>"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.1.2"
Flask-Login = "^0.6.1"
Flask-Admin = "^1.6.0"
Flask-SQLAlchemy = "^2.5.1"
GitHub-Flask = "^3.2.0"
alembic = "^1.7.7"
Pillow = "^9.1.0"
WTForms = "<3.1.0" # pinned until flask-admin fixes https://github.com/flask-admin/flask-admin/issues/2391
simpleeval = "^0.9.12"
Flask-DebugToolbar = "^0.13.1"
pyzbar = "^0.1.9"
bokeh = "^2.4.2"
beautifulsoup4 = "^4.11.1"
python-barcode = "^0.13.1"
environs = "^9.5.0"
gunicorn = "^20.1.0"
lxml = "^4.8.0"
pytest = "^7.1.2"
SQLAlchemy = {extras = ["mypy"], version = "^1.4.39"}
Bootstrap-Flask = "^2.1.0"
psycopg2 = "^2.9.3"
WTForms-Alchemy = "^0.18.0"
python-dateutil = "^2.8.2"
alembic_autogenerate_enums = "^0.0.2"
werkzeug = "<3.0.0" # pinned until flask-login commit 7d98a49b is released

[tool.poetry.dev-dependencies]
mypy = "^0.950"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.10"
warn_no_return = true
warn_return_any = true
plugins = ["sqlalchemy.ext.mypy.plugin"]